### ISSUE TITLE
Got unknown column error after install

### ISSUE THREAD

**Issue by sdrenth** [ilyautkin/xPoller#4]
When debugging the xPoller snippet I got the following mysql error:
`Unknown column 'DISTINCT xpAllAnswers.id' in 'field list'`

```
$q = $modx->newQuery('xpOption');
$q->where(array('qid' => $id));
$q->select('`xpOption`.`id`, `xpOption`.`qid`, `xpOption`.`option`, `xpOption`.`rank`,
            `xpOption`.`right`, `xpQuestion`.`text`, COUNT(DISTINCT `xpAnswer`.`uid`) as `votes`,
            COUNT(`DISTINCT xpAllAnswers`.`id`) as `total`');
$q->leftJoin('xpQuestion', 'xpQuestion', array('`xpOption`.`qid` = `xpQuestion`.`id`'));
$q->leftJoin('xpAnswer',   'xpAnswer',   array('`xpAnswer`.`oid` = `xpOption`.`id`'));
$q->leftJoin('xpAnswer',   'xpAllAnswers', array('`xpAllAnswers`.`qid` = `xpQuestion`.`id`'));
$q->groupby('`xpOption`.`id`');
$q->sortby('`xpOption`.`id`', 'ASC');
$q->prepare();

print "<pre>";
echo $q->toSQL();
print "</pre>";
exit;
```

**Comment by mmd-igor** [comment]
Должно быть вот так
```
...
COUNT(DISTINCT `xpAllAnswers`.`id`) as `total`');
...
```

**Comment by ilyautkin** [comment]
> Должно быть вот так
> 
> ```
> ...
> COUNT(DISTINCT `xpAllAnswers`.`id`) as `total`');
> ...
> ```

Спасибо, исправил, выпустил новую версию

**Comment by mmd-igor** [comment]
Ну, раз так оперативно реагируешь, то почему до кучи не исправлена ошибка,
о которой здесь же писали, - ...map.. файл, phptype = string, a не text.

чт, 29 апр. 2021 г., 09:57 Ilya Utkin ***@***.***>:

**Comment by mmd-igor** [comment]
И, надеюсь, последнее.

Чанк из коробки tpl.xPoller.form.outer содержит

...
<form role="form” action=“[[~[[*id]]]]”  method="post" class="xPolls”>
…

Не знаю как на других инстансах, на моем modx эта конструкция не имеет начального слета, то есть, если мой вызов твоего сниппета идет на странице www.domain.com/test <http://www.domain.com/test>, то форма сабмитится вот сюда www.domain.com/test/test <http://www.domain.com/test/test> 

То есть, из коробки твой компонент не завелся по трем пунктам. Допилил, конечно, но не по феншую в паблике так держать. 

PS. Кстати, похоже, твое наследие поддерживаю cyprusbutterfly.com <http://cyprusbutterfly.com/>.cy - по косвенным признакам ты поучаствовал :)

**Comment by ilyautkin** [comment]
> Ну, раз так оперативно реагируешь, то почему до кучи не исправлена ошибка, о которой здесь же писали, - ...map.. файл, phptype = string, a не text. 

Это тоже исправлено.

**Comment by ilyautkin** [comment]
> И, надеюсь, последнее. Чанк из коробки tpl.xPoller.form.outer содержит ... <form role="form” action=“[[~[[*id]]]]” method="post" class="xPolls”> … Не знаю как на других инстансах, на моем modx эта конструкция не имеет начального слета, то есть, если мой вызов твоего сниппета идет на странице [www.domain.com/test](http://www.domain.com/test) <http://www.domain.com/test>, то форма сабмитится вот сюда [www.domain.com/test/test](http://www.domain.com/test/test) <http://www.domain.com/test/test> То есть, из коробки твой компонент не завелся по трем пунктам. Допилил, конечно, но не по феншую в паблике так держать.

А это похоже, что у тебя не указан тег `<base>`.

**Comment by mmd-igor** [comment]
Ну так сознательно не указан, а полагаться на то, что у меня указано, а что нет, зачем.

Ладно, спасибо за компонент. Удачи!

С уважением, Игорь
